//
//  CatalogerInvocation.swift
//  Cataloger
//
//  Created by James Lawton on 3/24/17.
//  Copyright © 2017 James Lawton. All rights reserved.
//

import Foundation

struct CatalogerInvocation {
    let commandLine: String
    let catalogerRepository: String
    let date: Date

    init(verb: String, arguments: [String]) {
        commandLine = ([Cataloger.executableName, verb] + arguments).joined(separator: " ")
        catalogerRepository = Cataloger.repository
        date = Date()
    }

    var day: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        return formatter.string(from: date)
    }

    var swiftHeader: String {
        return "// Generated by Cataloger (\(catalogerRepository))\n"
            //+  "// \(day)\n"
            +  "//\n"
            +  "//   \(commandLine)\n"
            +  "//\n"
    }

    var objcHeader: String {
        return swiftHeader
    }
}
